// NexCargo MOD-016 — Provider Adapter Tests (C5-I)
// C5 Increment 1 — Authorized per HAO-C5-001 (2026-09-09)
// Tests: StubEmailProviderAdapter implementation, interface contract validation

import { describe, it, expect } from 'vitest';
import { NotificationChannel } from '@/shared/types/enums';
import {
  NotificationProviderAdapter,
  SendNotificationParams,
  ProviderSendResult,
  ProviderCredentialConfig,
  StubEmailProviderAdapter,
} from '../infrastructure/adapters/notification-provider-adapter';

describe('MOD-016 Provider Adapter Interface & Mock', () => {
  describe('StubEmailProviderAdapter implements NotificationProviderAdapter', () => {
    const adapter = new StubEmailProviderAdapter();

    it('should implement send() method', async () => {
      const params: SendNotificationParams = {
        recipient: 'test@example.com',
        channelType: NotificationChannel.EMAIL,
        title: 'Test Subject',
        body: 'Test body content.',
        correlationId: 'corr-001',
        priorityLevel: 'MEDIUM',
      };

      const result = await adapter.send(params);

      expect(result).toBeDefined();
      expect(result.status).toBeOneOf(['SUCCESS', 'FAILED', 'PENDING'] as const);
      expect(result.timestamp).toBeInstanceOf(Date);
      // May or may not have providerReferenceId depending on success/failure
      if (result.status === 'SUCCESS') {
        expect(result.providerReferenceId).toBeDefined();
        expect(typeof result.providerReferenceId).toBe('string');
      }
    });

    it('should implement verifyDelivery() method', async () => {
      // Verify a reference that was generated by this stub
      const stubRef = 'STUB-test-reference-uuid';
      const result = await adapter.verifyDelivery(stubRef);

      expect(result.status).toBe('SUCCESS');
      expect(result.providerReferenceId).toBe(stubRef);
    });

    it('should return FAILED for unknown provider references in verifyDelivery', async () => {
      const result = await adapter.verifyDelivery('UNKNOWN-ref-123');

      expect(result.status).toBe('FAILED');
      expect(result.errorMessage).toContain('Unknown provider reference');
    });

    it('should implement getErrorMappings() method', () => {
      const mappings = adapter.getErrorMappings();

      expect(Array.isArray(mappings)).toBe(true);
      expect(mappings.length).toBeGreaterThan(0);

      for (const mapping of mappings) {
        expect(mapping).toHaveProperty('providerErrorCode');
        expect(mapping).toHaveProperty('nexcargoErrorCode');
        expect(mapping).toHaveProperty('message');
        expect(typeof mapping.providerErrorCode).toBe('string');
        expect(typeof mapping.nexcargoErrorCode).toBe('string');
        expect(typeof mapping.message).toBe('string');
      }
    });

    it('should implement validateCredentials() method', () => {
      const validConfig: ProviderCredentialConfig = {
        providerId: 'STUB_EMAIL',
        apiKey: 'dummy-key',
        apiUrl: 'https://example.test/api',
      };

      expect(adapter.validateCredentials(validConfig)).toBe(true);
    });

    it('should reject empty providerId in validateCredentials', () => {
      const invalidConfig: ProviderCredentialConfig = {
        providerId: '',
      };

      expect(adapter.validateCredentials(invalidConfig)).toBe(false);
    });
  });

  describe('ProviderSendResult type contract', () => {
    it('status must be one of SUCCESS, FAILED, or PENDING', () => {
      const validStatuses: Array<'SUCCESS' | 'FAILED' | 'PENDING'> = ['SUCCESS', 'FAILED', 'PENDING'];

      for (const status of validStatuses) {
        const result: ProviderSendResult = {
          status,
          timestamp: new Date(),
        };

        expect(result.status).toBe(status);
      }
    });

    it('must include timestamp', () => {
      const result: ProviderSendResult = {
        status: 'SUCCESS',
        timestamp: new Date('2026-09-09T12:00:00Z'),
      };

      expect(result.timestamp).toBeInstanceOf(Date);
    });

    it('providerReferenceId is optional on success', () => {
      const withRef: ProviderSendResult = {
        status: 'SUCCESS',
        providerReferenceId: 'PROV-12345',
        timestamp: new Date(),
      };

      expect(withRef.providerReferenceId).toBe('PROV-12345');

      // TypeScript allows omitting it
      const withoutRef: ProviderSendResult = {
        status: 'SUCCESS',
        timestamp: new Date(),
      };

      expect(withoutRef.providerReferenceId).toBeUndefined();
    });

    it('errorMessage is optional and typically present only on FAILED status', () => {
      const failedResult: ProviderSendResult = {
        status: 'FAILED',
        errorMessage: 'Simulated failure for testing',
        timestamp: new Date(),
      };

      expect(failedResult.errorMessage).toBe('Simulated failure for testing');
    });
  });

  describe('Deterministic mock behavior (NO EXTERNAL CALLS)', () => {
    it('should never throw errors during send operations', async () => {
      const adapter = new StubEmailProviderAdapter();

      const params: SendNotificationParams = {
        recipient: 'user@test.com',
        channelType: NotificationChannel.EMAIL,
        title: 'Subject line',
        body: 'Message body text.',
        correlationId: 'corr-random-id',
        priorityLevel: 'LOW',
      };

      // Should complete without throwing even under network-unavailable conditions
      await expect(adapter.send(params)).resolves.not.toThrow();
    });

    it('verifyDelivery should handle all edge cases gracefully', async () => {
      const adapter = new StubEmailProviderAdapter();

      await expect(adapter.verifyDelivery('')).resolves.not.toThrow();
      await expect(adapter.verifyDelivery(undefined as never)).resolves.not.toThrow();
      await expect(adapter.verifyDelivery(null as never)).resolves.not.toThrow();
    });
  });
});
