// NexCargo MOD-001 MatchProposal Type Definition
// Authorized by HAO-WAVE1-001 — Wave 1 Increment 1: Domain Foundations
// Per MOD-001 §5.3 and §3.2 state machine

import { BaseEntity } from '@/shared/base-classes/base-entity';
import { MatchStatus } from '../enums';

/**
 * Match Proposal — a structured pairing between a listing and an offer.
 * 
 * State machine (MOD-001 §3.2):
 *   PROPOSED → ACCEPTED | REJECTED
 * 
 * Acceptance rule (MOD-001 §5.3):
 *   - A match proposal is generated only for PUBLISHED listings
 *   - The shipper explicitly accepts a proposal, which transitions the listing to BOOKED
 *     and triggers handoff to MOD-002 (Booking & Contract Management)
 */
export interface MatchProposal extends BaseEntity {
  /** Unique identifier for this match proposal */
  matchId: string;

  /** The listing being matched */
  listingId: string;

  /** The offer being proposed as a match */
  offerId: string;

  /**
   * Conceptual score generated by AI-EPRS matching engine.
   * Range: 0–100, computed per MOD-001 §6.4.4 numerical weighting model.
   * CompositeScore = (WeightedScore / 177) × 100
   */
  matchScore: number;

  /**
   * Relative rank among all offers for that listing.
   * Top 5 transporters are highlighted as "Recommended" per MOD-001 §6.5 Step 4.
   */
  rankingPosition: number;

  /** Current state of the match proposal */
  status: MatchStatus;

  /** Optional reasoning trace for the match score (explainability) */
  reasoningTrace?: string;
}
