// NexCargo MOD-004 — MOD-004 BC Coordination Contracts (Design-Time)
// Wave 2 — Stage 2B, Increment 2 — Authorized per HAOSTAGE2B-AUTH-001 (D-S2B-001)
// Reference: MOD-004 §8 Event Model, §9 Integration Boundaries
//
// Governance note: These are design-time data contracts only. No runtime event emission mechanism.
// They define the interface surface required for BC coordination between MOD-004 and other modules.
// No EventEmitter, EventBus, emit(), or subscribe() calls appear in this file.

/**
 * ContractDocumentGeneratedPayload — Document structure generated by MOD-004 when a contract is finalized.
 * CONSUMED BY MOD-002 from MOD-004 outputs.
 * Per MOD-004 §8: "DocumentSigned consumed by MOD-002 → contract validation and contract document generation."
 */
export interface ContractDocumentGeneratedPayload {
  /** The contract being documented */
  contractId: string;
  /** The booking reference linked to this contract */
  bookingId: string;
  /** Document type identifier */
  documentType: 'CONTRACT';
  /** Pointer to the generated contract document storage */
  fileReference: string;
  /** Integrity checksum */
  fileHash: string;
  /** Signatory information embedded in the document */
  signatoriesCount: number;
  /** ISO 8601 generation timestamp */
  generatedAt: string;
}

/**
 * PodDocumentLinkageRequest — Request from MOD-003 to create POD document linkage in MOD-004.
 * CONSUMED BY MOD-004 from MOD-003 signals.
 * Per MOD-004 §8: "POD submitted / POD verified consumed by MOD-003 → shipment verification checkpoints and Proof of Delivery document linking."
 */
export interface PodDocumentLinkageRequest {
  /** The tracking record associated with this POD */
  trackingId: string;
  /** The contract reference */
  contractId: string;
  /** The booking reference */
  bookingId: string;
  /** POD-specific file reference created by MOD-003 */
  podFileReference: string;
  /** POD integrity hash created by MOD-003 */
  podFileHash: string;
  /** Timestamp when POD was submitted */
  submittedAt: string; // ISO 8601
}

/**
 * ExpiryReminderNotificationData — Notification payload for document expiry reminders.
 * PRODUCED BY MOD-004, CONSUMED BY MOD-016 (via notification triggers).
 * Per MOD-004 §8: "DocumentExpiring / DocumentExpired consumed by MOD-016 → notification triggers (expiry reminders, signing requests)."
 */
export interface ExpiryReminderNotificationData {
  /** The document whose expiry is approaching or has passed */
  documentId: string;
  /** Type of document */
  documentType: string;
  /** Linked entity ID for context */
  linkedEntityId: string;
  /** Whether expiry is imminent or has passed */
  isExpired: boolean;
  /** Days until/after expiry */
  daysUntilExpiry: number;
  /** Operational impact level */
  operationalImpact: string;
  /** ISO 8601 timestamp of notification generation */
  notifiedAt: string;
}
