// NexCargo MOD-001 Marketplace Repository Interface
// Authorized by HAO-WAVE1-001 — Wave 1 Increment 1: Domain Foundations
// Extends SupabaseBaseRepository per PROMPT 1 architecture template

import { SupabaseBaseRepository } from '@/infrastructure/repositories/base-repository';
import { ShipmentListing } from '../../domain/types/listings';
import { TransportOffer } from '../../domain/types/offers';
import { MatchProposal } from '../../domain/types/matches';
import { AdvisoryQuote } from '../../domain/types/quotes';
import { ListingStatus, OfferStatus, MatchStatus } from '../../domain/enums';

/**
 * Marketplace repository interface for CRUD operations on marketplace entities.
 * 
 * Per MOD-001 architecture:
 *   - Listings are managed by shippers (MOD-001)
 *   - Offers are submitted by transporters in response to listings (MOD-001)
 *   - Match proposals are generated by the matching engine (advisory only) (MOD-001)
 *   - Advisory quotes are generated by AI-EPRS assistance (MOD-001 §5.4)
 * 
 * Implementation note:
 *   This interface extends SupabaseBaseRepository for listing operations.
 *   Offer, Match, and Quote repositories are defined separately due to
 *   distinct table schemas and access patterns.
 */
export interface IMarketplaceRepository extends SupabaseBaseRepository<ShipmentListing> {
  /**
   * Find all listings matching given status filter.
   */
  findByStatus(status: ListingStatus): Promise<ShipmentListing[]>;

  /**
   * Find all active (published) listings.
   */
  findPublished(): Promise<ShipmentListing[]>;

  /**
   * Find listings by shipper ID.
   */
  findByShipper(shipperId: string): Promise<ShipmentListing[]>;

  /**
   * Count total published listings.
   */
  countPublished(): Promise<number>;
}

/**
 * Offer repository interface for offer lifecycle management.
 */
export interface IOfferRepository extends SupabaseBaseRepository<TransportOffer> {
  /**
   * Find all offers for a specific listing.
   */
  findByListing(listingId: string): Promise<TransportOffer[]>;

  /**
   * Find accepted offer for a listing (at most one at any time).
   */
  findAcceptedByListing(listingId: string): Promise<TransportOffer | null>;

  /**
   * Find offers by transporter ID.
   */
  findByTransporter(transporterId: string): Promise<TransportOffer[]>;
}

/**
 * Match proposal repository interface.
 */
export interface IMatchRepository extends SupabaseBaseRepository<MatchProposal> {
  /**
   * Find all match proposals for a specific listing.
   */
  findByListing(listingId: string): Promise<MatchProposal[]>;

  /**
   * Find all accepted match proposals.
   */
  findAccepted(): Promise<MatchProposal[]>;

  /**
   * Find match proposals by offer ID.
   */
  findByOffer(offerId: string): Promise<MatchProposal[]>;
}

/**
 * Advisory quote repository interface.
 */
export interface IQuoteRepository extends SupabaseBaseRepository<AdvisoryQuote> {
  /**
   * Find advisory quote for a specific listing.
   */
  findByListing(listingId: string): Promise<AdvisoryQuote | null>;

  /**
   * Find all quotes with confidence above threshold.
   */
  findWithMinConfidence(minConfidence: number): Promise<AdvisoryQuote[]>;
}
